name: Kubernetes CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Check Kubernetes files
      run: |
        ls k8s
        cat k8s/deployment.yaml
        cat k8s/service.yaml
